#!/usr/bin/env node
/**
 * build.js — bundles src/ into one Tampermonkey userscript, via esbuild.
 *
 *   node build.js            patch bump   3.8.0 → 3.8.1
 *   node build.js --minor    minor bump
 *   node build.js --major    major bump
 *   node build.js --same     no bump (local testing only)
 *   node build.js --watch    rebuild on save, no bump
 *
 * WHY THE BUMP MATTERS: Tampermonkey only pulls a new version when @version is
 * HIGHER than what it has installed. Push without bumping and nothing updates
 * anywhere — so the bump is automatic here.
 *
 * HOW THE BUNDLE IS SHAPED. src/ is real ES modules now; execution order is
 * the import graph, with boot.js as the entry. Two things esbuild cannot do
 * are done here:
 *
 *  - `src/manifest.js` is GENERATED before each build: side-effect imports of
 *    every file under subjects/ and tools/ (recursively), so a new capability
 *    is still one new file that nothing else has to name.
 *  - `src/banner.js` is NOT a module. Its guard has to abort the whole overlay
 *    before any module evaluates, and imports hoist — so its text is injected
 *    at the top of the wrapper IIFE that encloses esbuild's output.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const cp = require('child_process');
const esbuild = require('esbuild');

const ROOT = __dirname;
const SRC = path.join(ROOT, 'src');
const DIST = path.join(ROOT, 'dist');
const cfg = JSON.parse(fs.readFileSync(path.join(ROOT, 'userscript.json'), 'utf8'));
/** Placeholder in src/core/config.js, replaced with the real version at bundle time. */
const VERSION_TOKEN = '__VERSION__';

function bump(v, kind) {
  const [a, b, c] = v.split('.').map(Number);
  if (kind === 'major') return `${a + 1}.0.0`;
  if (kind === 'minor') return `${a}.${b + 1}.0`;
  if (kind === 'same') return v;
  return `${a}.${b}.${c + 1}`;
}

function metaBlock(version) {
  const raw = `${cfg.rawBase}/${cfg.distFile}`;
  const rows = [
    ['name', cfg.name],
    ['namespace', cfg.namespace],
    ['version', version],
    ['description', cfg.description],
    ['author', cfg.author],
    ...cfg.match.map((m) => ['match', m]),
    ...(cfg.grant?.length ? cfg.grant : ['none']).map((g) => ['grant', g]),
    ...(cfg.noframes ? [['noframes', '']] : []),
    ['run-at', 'document-idle'],
    ['updateURL', `${cfg.rawBase}/${cfg.metaFile}`],
    ['downloadURL', raw],
  ];
  const pad = Math.max(...rows.map(([k]) => k.length)) + 2;
  return ['// ==UserScript==',
    ...rows.map(([k, v]) => `// @${k.padEnd(pad)}${v}`.trimEnd()),
    '// ==/UserScript=='].join('\n');
}

/** Every .js under a src subdir, recursive, sorted — the auto-discovery. */
function glob(dir) {
  const out = [];
  const walk = (d, base) => {
    for (const e of fs.readdirSync(d, { withFileTypes: true })) {
      const rel = base ? `${base}/${e.name}` : e.name;
      if (e.isDirectory()) walk(path.join(d, e.name), rel);
      else if (e.name.endsWith('.js')) out.push(rel);
    }
  };
  const abs = path.join(SRC, dir);
  if (fs.existsSync(abs)) walk(abs, dir);
  return out.sort();
}

function genManifest() {
  const files = [...glob('subjects'), ...glob('tools')];
  const body = ['// GENERATED by build.js — do not edit, do not commit.',
    '// Side-effect imports: registering a subject or tool IS its module body,',
    '// so a new capability stays one new file that nothing else has to name.',
    ...files.map((f) => `import './${f}';`), ''].join('\n');
  fs.writeFileSync(path.join(SRC, 'manifest.js'), body);
  return files.length;
}

function build(kind) {
  const version = bump(cfg.version, kind);
  const discovered = genManifest();

  let bundled;
  try {
    bundled = esbuild.buildSync({
      entryPoints: [path.join(SRC, 'boot.js')],
      bundle: true,
      format: 'iife',
      charset: 'utf8',       // the bar is drawn in glyphs; keep them readable
      legalComments: 'none',
      write: false,
      target: 'es2020',
    }).outputFiles[0].text;
  } catch (e) {
    console.error('✗ esbuild failed:\n' + (e.errors || [e.message]).map((x) =>
      typeof x === 'string' ? x : `${x.text} (${x.location?.file}:${x.location?.line})`).join('\n'));
    process.exit(1);
  }

  if (!bundled.includes(VERSION_TOKEN)) {
    console.error(`✗ ${VERSION_TOKEN} not found in the bundle — nothing would tell the ` +
                  'overlay its version, and a stale install would look current');
    process.exit(1);
  }
  bundled = bundled.replace(VERSION_TOKEN, version);

  const banner = fs.readFileSync(path.join(SRC, 'banner.js'), 'utf8');
  const docs = fs.readFileSync(path.join(ROOT, 'DOCS.txt'), 'utf8').trim();
  const out = `${metaBlock(version)}\n\n/*\n${docs}\n*/\n\n` +
    `(function () {\n  'use strict';\n${banner}\n${bundled}})();\n`;

  fs.mkdirSync(DIST, { recursive: true });
  const distPath = path.join(DIST, cfg.distFile);
  fs.writeFileSync(distPath, out);
  fs.writeFileSync(path.join(DIST, cfg.metaFile), metaBlock(version) + '\n');

  // never ship something that does not parse
  try {
    cp.execSync(`node --check "${distPath}"`, { stdio: 'pipe' });
  } catch (e) {
    console.error('✗ syntax error in bundle:\n' + e.stderr.toString());
    process.exit(1);
  }

  if (kind !== 'same') {
    cfg.version = version;
    fs.writeFileSync(path.join(ROOT, 'userscript.json'), JSON.stringify(cfg, null, 2) + '\n');
  }
  const kb = (Buffer.byteLength(out) / 1024).toFixed(1);
  console.log(`✓ v${version}  ${discovered} discovered + core → dist/${cfg.distFile}  (${kb} KB)`);
  return distPath;
}

const arg = process.argv[2] || '';
if (arg === '--watch') {
  build('same');
  console.log('watching src/ …');
  let t = null;
  const rebuild = () => { clearTimeout(t); t = setTimeout(() => {
    try { build('same'); } catch {}
  }, 120); };
  fs.watch(SRC, { recursive: true }, (ev, f) => { if (f !== 'manifest.js') rebuild(); });
} else {
  build(arg.replace('--', '') || 'patch');
}
