#!/usr/bin/env node
/**
 * build.js — bundles src/ into one Tampermonkey userscript, via esbuild.
 *
 *   node build.js            patch bump   3.8.0 → 3.8.1
 *   node build.js --minor    minor bump
 *   node build.js --major    major bump
 *   node build.js --same     no bump (local testing only)
 *   node build.js --watch    rebuild on save, no bump
 *
 * WHY THE BUMP MATTERS: Tampermonkey only pulls a new version when @version is
 * HIGHER than what it has installed. Push without bumping and nothing updates
 * anywhere — so the bump is automatic here.
 *
 * HOW THE BUNDLE IS SHAPED. src/ is real ES modules now; execution order is
 * the import graph, with boot.js as the entry. Two things esbuild cannot do
 * are done here:
 *
 *  - `src/manifest.js` is GENERATED before each build: side-effect imports of
 *    every file under subjects/ and tools/ (recursively), so a new capability
 *    is still one new file that nothing else has to name.
 *  - `src/banner.js` is NOT a module. Its guard has to abort the whole overlay
 *    before any module evaluates, and imports hoist — so its text is injected
 *    at the top of the wrapper IIFE that encloses esbuild's output.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const cp = require('child_process');
const esbuild = require('esbuild');

const ROOT = __dirname;
const SRC = path.join(ROOT, 'src');
const DIST = path.join(ROOT, 'dist');
const cfg = JSON.parse(fs.readFileSync(path.join(ROOT, 'userscript.json'), 'utf8'));
/** Placeholder in src/core/config.js, replaced with the real version at bundle time. */
const VERSION_TOKEN = '__VERSION__';
const META_TOKEN = '__META_URL__';
const INSTALL_TOKEN = '__INSTALL_URL__';

function bump(v, kind) {
  const [a, b, c] = v.split('.').map(Number);
  if (kind === 'major') return `${a + 1}.0.0`;
  if (kind === 'minor') return `${a}.${b + 1}.0`;
  if (kind === 'same') return v;
  return `${a}.${b}.${c + 1}`;
}

function metaBlock(version) {
  const raw = `${cfg.rawBase}/${cfg.distFile}`;
  const rows = [
    ['name', cfg.name],
    ['namespace', cfg.namespace],
    ['version', version],
    ['description', cfg.description],
    ['author', cfg.author],
    ...cfg.match.map((m) => ['match', m]),
    ...(cfg.grant?.length ? cfg.grant : ['none']).map((g) => ['grant', g]),
    // @connect whitelists the update checker's host at install time, so the
    // manager's network door opens with NO per-use prompt — and only to here
    ...(cfg.connect || []).map((c) => ['connect', c]),
    ...(cfg.noframes ? [['noframes', '']] : []),
    ['run-at', 'document-idle'],
    ['updateURL', `${cfg.rawBase}/${cfg.metaFile}`],
    ['downloadURL', raw],
  ];
  const pad = Math.max(...rows.map(([k]) => k.length)) + 2;
  return ['// ==UserScript==',
    ...rows.map(([k, v]) => `// @${k.padEnd(pad)}${v}`.trimEnd()),
    '// ==/UserScript=='].join('\n');
}

/** Every .js under a src subdir, recursive, sorted — the auto-discovery. */
function glob(dir) {
  const out = [];
  const walk = (d, base) => {
    for (const e of fs.readdirSync(d, { withFileTypes: true })) {
      const rel = base ? `${base}/${e.name}` : e.name;
      if (e.isDirectory()) walk(path.join(d, e.name), rel);
      else if (e.name.endsWith('.js')) out.push(rel);
    }
  };
  const abs = path.join(SRC, dir);
  if (fs.existsSync(abs)) walk(abs, dir);
  return out.sort();
}

function genManifest() {
  // tools register through their index; a shared subject (none today —
  // both current backends have a single consumer and live inside it) would
  // land in subjects/ and be picked up here the day it exists
  const files = [...glob('subjects'),
                 ...glob('tools').filter((f) => f.endsWith('/index.js'))];
  const body = ['// GENERATED by build.js — do not edit, do not commit.',
    '// Side-effect imports: registering a subject or tool IS its module body,',
    '// so a new capability stays one new file that nothing else has to name.',
    ...files.map((f) => `import './${f}';`), ''].join('\n');
  fs.writeFileSync(path.join(SRC, 'manifest.js'), body);
  return files.length;
}

function build(kind) {
  const version = bump(cfg.version, kind);
  const discovered = genManifest();

  let bundled;
  try {
    bundled = esbuild.buildSync({
      entryPoints: [path.join(SRC, 'boot.js')],
      bundle: true,
      format: 'iife',
      charset: 'utf8',       // the bar is drawn in glyphs; keep them readable
      legalComments: 'none',
      write: false,
      target: 'es2020',
    }).outputFiles[0].text;
  } catch (e) {
    console.error('✗ esbuild failed:\n' + (e.errors || [e.message]).map((x) =>
      typeof x === 'string' ? x : `${x.text} (${x.location?.file}:${x.location?.line})`).join('\n'));
    process.exit(1);
  }

  if (!bundled.includes(VERSION_TOKEN)) {
    console.error(`✗ ${VERSION_TOKEN} not found in the bundle — nothing would tell the ` +
                  'overlay its version, and a stale install would look current');
    process.exit(1);
  }
  bundled = bundled.replace(VERSION_TOKEN, version)
    .replace(META_TOKEN, `${cfg.rawBase}/${cfg.metaFile}`)
    .replace(INSTALL_TOKEN, `${cfg.rawBase}/${cfg.distFile}`);

  const banner = fs.readFileSync(path.join(SRC, 'banner.js'), 'utf8');
  const docs = fs.readFileSync(path.join(ROOT, 'DOCS.txt'), 'utf8').trim();
  const out = `${metaBlock(version)}\n\n/*\n${docs}\n*/\n\n` +
    `(function () {\n  'use strict';\n${banner}\n${bundled}})();\n`;

  /* dist/ is organised by GATE:
       dist/script/            the userscript — canonical home
       dist/browser-extension/ the extension + its install ZIP
       dist/debug-overlay.*    LEGACY BRIDGE, never remove: every install
                               from before the restructure polls THIS path
                               forever. The copies are byte-identical and
                               their headers point at dist/script/, so an
                               old install's next update quietly migrates
                               it to the new home. Deleting them is the
                               dead-@updateURL failure — silent, forever. */
  fs.mkdirSync(DIST, { recursive: true });
  const SCRIPT = path.join(DIST, 'script');
  fs.mkdirSync(SCRIPT, { recursive: true });
  const distPath = path.join(SCRIPT, cfg.distFile);
  fs.writeFileSync(distPath, out);
  fs.writeFileSync(path.join(SCRIPT, cfg.metaFile), metaBlock(version) + '\n');
  fs.writeFileSync(path.join(DIST, cfg.distFile), out);
  fs.writeFileSync(path.join(DIST, cfg.metaFile), metaBlock(version) + '\n');

  // never ship something that does not parse
  try {
    cp.execSync(`node --check "${distPath}"`, { stdio: 'pipe' });
  } catch (e) {
    console.error('✗ syntax error in bundle:\n' + e.stderr.toString());
    process.exit(1);
  }

  if (kind !== 'same') {
    cfg.version = version;
    fs.writeFileSync(path.join(ROOT, 'userscript.json'), JSON.stringify(cfg, null, 2) + '\n');
  }
  /* THE SECOND GATE — an unpacked browser extension, from the SAME bundle.
     One core, two wrappers: the userscript above and this content script are
     byte-identical inside, which is what makes drift impossible — there is
     no "extension version of the code" to disagree with the userscript.
     Load it via chrome://extensions → Developer mode → Load unpacked. */
  /* ONE design system for the three extension pages, inlined rather than
     shipped. Each page used to invent its own button, its own greys and its
     own radii — which is how the 24px target floor got breached in three
     files independently. A shipped .css would mean another entry in
     files.json, in the installer's embed and in the updater's write list;
     inlining costs nothing and keeps one source of truth. */
  const SHARED = fs.readFileSync(
    path.join(ROOT, 'browser-extension-source', 'shared.css'), 'utf8');
  const withShared = (html) => {
    if (!html.includes('<style>')) {
      console.error('✗ a page has no <style> to inline the shared sheet into');
      process.exit(1);
    }
    return html.replace('<style>', '<style>\n/* --- shared.css (inlined by build.js) --- */\n' +
      SHARED + '\n/* --- end shared.css --- */\n');
  };

  const EXT = path.join(DIST, 'browser-extension');
  /* Cleared, not merged. Every file in here is written below, so anything
     already present is from an older build — and a rename would otherwise
     leave both spellings on disk AND inside the shipped ZIP, which is how a
     dead file reaches a user's install folder in the first place. (The
     user's OWN folder is swept by name instead: this directory the build
     owns outright, that one it does not.) */
  fs.rmSync(EXT, { recursive: true, force: true });
  fs.mkdirSync(EXT, { recursive: true });
  fs.writeFileSync(path.join(EXT, 'content.js'),
    `/* Debug Overlay v${version} — extension gate; same bundle as the userscript */\n` +
    `(function () {\n  'use strict';\n${banner}\n${bundled}})();\n`);
  fs.writeFileSync(path.join(EXT, 'manifest.json'), JSON.stringify({
    manifest_version: 3,
    name: cfg.name,
    version,
    description: cfg.description,
    content_scripts: [{ matches: ['<all_urls>'], js: ['content.js'], run_at: 'document_idle' }],
    // the update checker's CSP-immune door: the worker fetches, pages cannot block it
    host_permissions: [`${new URL(cfg.rawBase).origin}/*`],
    background: { service_worker: 'sw.js' },
    // options_ui is CHROME's key; the page it opens is ours, and it is the
    // update screen, so that is what it is called
    options_ui: { page: 'update.html', open_in_tab: true },
    /* THE SIDE PANEL — the extension gate's bigger face. The toolbar button
       opens it (sw.js declares that); it mirrors the in-page panel over a
       port and survives the page refresh the in-page bar cannot. */
    action: { default_title: `${cfg.name} — open the side panel`,
              default_icon: { 16: 'icon16.png', 32: 'icon32.png',
                              48: 'icon48.png', 128: 'icon128.png' } },
    /* the options page's own logo (lucide bug on the brand tile), rendered
       to PNG by browser-extension-source/make-icons.js — generated once and
       committed, so the build never needs an image toolchain */
    icons: { 16: 'icon16.png', 32: 'icon32.png', 48: 'icon48.png', 128: 'icon128.png' },
    side_panel: { default_path: 'side-panel.html' },
    permissions: ['sidePanel'],
  }, null, 2) + '\n');
  fs.writeFileSync(path.join(EXT, 'sw.js'),
    `// Debug Overlay service worker — the extension's network door.\n` +
    `// A page's CSP cannot reach in here, so update checks work everywhere.\n` +
    `chrome.runtime.onMessage.addListener((msg, sender, respond) => {\n` +
    `  if (msg && msg.type === 'debug-overlay-fetch' && typeof msg.url === 'string' &&\n` +
    `      msg.url.startsWith(${JSON.stringify(cfg.rawBase + '/')})) {\n` +
    `    fetch(msg.url, { cache: 'no-store' })\n` +
    `      .then((r) => r.text()).then((text) => respond({ ok: true, text }))\n` +
    `      .catch((e) => respond({ ok: false, error: String(e) }));\n` +
    `    return true;   // async response\n` +
    `  }\n` +
    `  if (msg && msg.type === 'debug-overlay-open-options') {\n` +
    `    chrome.runtime.openOptionsPage();\n` +
    `  }\n` +
    `});\n` +
    `// the toolbar button opens the side panel (declared, so it needs no handler);\n` +
    `// guarded because browsers without a side panel still run everything else\n` +
    `chrome.sidePanel?.setPanelBehavior({ openPanelOnActionClick: true }).catch(() => {});\n`);
  /* the self-updater — real template files in browser-extension-source/,
     base substituted here. SOURCE and OUTPUT deliberately do NOT share a
     name: two folders both called browser-extension read as a duplicate in
     any file explorer, when one is what you edit and the other is what the
     build emits — the same relationship src/ has to dist/. */
  const extBase = cfg.rawBase.replace(/\/script$/, '/browser-extension');
  fs.writeFileSync(path.join(EXT, 'update.html'), withShared(
    fs.readFileSync(path.join(ROOT, 'browser-extension-source', 'update', 'update.html'), 'utf8')));
  // the Windows helper: rides inside the ZIP so install is download →
  // extract → double-click → the two clicks the browser reserves for humans
  fs.copyFileSync(path.join(ROOT, 'browser-extension-source', 'installer', 'install.bat'),
    path.join(EXT, 'install.bat'));
  fs.writeFileSync(path.join(EXT, 'update.js'),
    fs.readFileSync(path.join(ROOT, 'browser-extension-source', 'update', 'update.js'), 'utf8')
      .replace('__EXT_BASE__', extBase));
  /* the side panel: its page is copied, its program is BUNDLED — side-panel.js
     imports the shared src/core/protocol.js, which is the whole reason the
     two faces cannot drift: one vocabulary file, two importers. */
  fs.writeFileSync(path.join(EXT, 'side-panel.html'), withShared(
    fs.readFileSync(path.join(ROOT, 'browser-extension-source', 'side-panel', 'side-panel.html'), 'utf8')));
  for (const n of [16, 32, 48, 128]) {
    fs.copyFileSync(path.join(ROOT, 'browser-extension-source', 'icons', `icon${n}.png`),
      path.join(EXT, `icon${n}.png`));
  }
  let sidePanel;
  try {
    sidePanel = esbuild.buildSync({
      entryPoints: [path.join(ROOT, 'browser-extension-source', 'side-panel', 'side-panel.js')],
      bundle: true, format: 'iife', charset: 'utf8', legalComments: 'none',
      write: false, target: 'es2020',
    }).outputFiles[0].text;
  } catch (e) {
    console.error('✗ esbuild failed on the side panel:\n' + (e.errors || [e.message]).map((x) =>
      typeof x === 'string' ? x : `${x.text} (${x.location?.file}:${x.location?.line})`).join('\n'));
    process.exit(1);
  }
  if (!sidePanel.includes(VERSION_TOKEN)) {
    console.error('✗ __VERSION__ not found in the side panel bundle — it could not ' +
                  'tell a stale page from a current one');
    process.exit(1);
  }
  fs.writeFileSync(path.join(EXT, 'side-panel.js'), sidePanel.replace(VERSION_TOKEN, version));
  try {
    cp.execSync(`node --check "${path.join(EXT, 'content.js')}"`, { stdio: 'pipe' });
    cp.execSync(`node --check "${path.join(EXT, 'sw.js')}"`, { stdio: 'pipe' });
    cp.execSync(`node --check "${path.join(EXT, 'update.js')}"`, { stdio: 'pipe' });
    cp.execSync(`node --check "${path.join(EXT, 'side-panel.js')}"`, { stdio: 'pipe' });
    JSON.parse(fs.readFileSync(path.join(EXT, 'manifest.json'), 'utf8'));
  } catch (e) {
    console.error('✗ dist/browser-extension is broken:\n' + (e.stderr ? e.stderr.toString() : e.message));
    process.exit(1);
  }

  /* ONE LINK for the extension too. Chrome will not install from a URL
     outside its store, but it will happily Load-unpacked an extracted
     folder — so the build ships a ZIP of the extension at a stable raw URL,
     and installing becomes: download, extract, Load unpacked. The ZIP is
     written here in ~40 lines (store method, CRC32) because depending on
     a system zip binary would make the build machine-specific. */
  const zipStore = (files) => {
    const CRC = (() => {
      const T = new Int32Array(256);
      for (let n = 0; n < 256; n++) {
        let c = n;
        for (let k = 0; k < 8; k++) c = c & 1 ? 0xEDB88320 ^ (c >>> 1) : c >>> 1;
        T[n] = c;
      }
      return (buf) => {
        let c = -1;
        for (let i = 0; i < buf.length; i++) c = T[(c ^ buf[i]) & 0xFF] ^ (c >>> 8);
        return (c ^ -1) >>> 0;
      };
    })();
    const chunks = [];
    const central = [];
    let offset = 0;
    for (const [name, data] of files) {
      const nameB = Buffer.from(name);
      const crc = CRC(data);
      const local = Buffer.alloc(30);
      local.writeUInt32LE(0x04034b50, 0);
      local.writeUInt16LE(20, 4);                 // version needed
      local.writeUInt32LE(crc, 14);
      local.writeUInt32LE(data.length, 18);       // compressed (stored)
      local.writeUInt32LE(data.length, 22);       // uncompressed
      local.writeUInt16LE(nameB.length, 26);
      chunks.push(local, nameB, data);
      const cd = Buffer.alloc(46);
      cd.writeUInt32LE(0x02014b50, 0);
      cd.writeUInt16LE(20, 4); cd.writeUInt16LE(20, 6);
      cd.writeUInt32LE(crc, 16);
      cd.writeUInt32LE(data.length, 20);
      cd.writeUInt32LE(data.length, 24);
      cd.writeUInt16LE(nameB.length, 28);
      cd.writeUInt32LE(offset, 42);
      central.push(cd, nameB);
      offset += 30 + nameB.length + data.length;
    }
    const cdBuf = Buffer.concat(central);
    const eocd = Buffer.alloc(22);
    eocd.writeUInt32LE(0x06054b50, 0);
    eocd.writeUInt16LE(files.length, 8);
    eocd.writeUInt16LE(files.length, 10);
    eocd.writeUInt32LE(cdBuf.length, 12);
    eocd.writeUInt32LE(offset, 16);
    return Buffer.concat([...chunks, cdBuf, eocd]);
  };
  /* install.html — the no-cmd installer: a self-contained page carrying
     every runtime file inline, writing them out via the File System Access
     API. Exists because install.bat met a real machine where administrators
     disable the command prompt; a browser page they cannot disable. The
     JSON's '</' is escaped so no embedded file can close the script tag. */
  const RUNTIME = ['manifest.json', 'content.js', 'sw.js', 'update.html', 'update.js',
                   'side-panel.html', 'side-panel.js',
                   'icon16.png', 'icon32.png', 'icon48.png', 'icon128.png'];
  const BIN = (f) => /\.png$/i.test(f);
  /* files.json — the runtime file SET, published beside the files. The
     self-updater fetches THIS to learn what to write, because a baked-in
     list answers for the build that shipped it, not the one being fetched:
     the v3.8.98 updater's five-name list would have written the side panel's
     manifest while never fetching the side panel, leaving a folder Chrome
     refuses. The list names itself so the disk copy stays current too. */
  const SHIPPED = [...RUNTIME, 'files.json'];
  fs.writeFileSync(path.join(EXT, 'files.json'), JSON.stringify(SHIPPED, null, 2) + '\n');
  /* text files embed as strings; binaries as { b64 } — the installer
     decodes by shape, so a PNG survives the text-only page unhurt */
  const filesJson = JSON.stringify(Object.fromEntries(
    SHIPPED.map((f) => [f, BIN(f)
      ? { b64: fs.readFileSync(path.join(EXT, f)).toString('base64') }
      : fs.readFileSync(path.join(EXT, f), 'utf8')])))
    .replace(/<\//g, '<\\/');
  /* function replacement: the JSON is full of '$' sequences that string
     replacement would interpret as capture references and corrupt */
  fs.writeFileSync(path.join(EXT, 'install.html'),
    withShared(fs.readFileSync(path.join(ROOT, 'browser-extension-source', 'installer', 'install.html'), 'utf8'))
      .replace('const FILES = __FILES_JSON__;', () => `const FILES = ${filesJson};`));

  const extFiles = fs.readdirSync(EXT).sort()
    .filter((f) => !f.endsWith('.zip'))   // or the second build zips the zip
    .map((f) => [f, fs.readFileSync(path.join(EXT, f))]);
  fs.writeFileSync(path.join(EXT, 'debug-overlay-extension.zip'), zipStore(extFiles));

  const kb = (Buffer.byteLength(out) / 1024).toFixed(1);
  console.log(`✓ v${version}  ${discovered} discovered + core → dist/script/${cfg.distFile}  (${kb} KB)` +
    ` + dist/browser-extension/ (+ legacy bridge at dist/)`);
  return distPath;
}

const arg = process.argv[2] || '';
if (arg === '--watch') {
  build('same');
  console.log('watching src/ …');
  let t = null;
  const rebuild = () => { clearTimeout(t); t = setTimeout(() => {
    try { build('same'); } catch {}
  }, 120); };
  fs.watch(SRC, { recursive: true }, (ev, f) => { if (f !== 'manifest.js') rebuild(); });
} else {
  build(arg.replace('--', '') || 'patch');
}
