/* ======================================================================
  BOOT — the entry module: wire everything together and start

     Import order is not decorative. `./manifest.js` (generated by build.js)
     carries the side-effect registrations of every subject and tool, and it
     must run before initDom() builds the per-tool stylesheets. Everything
     else resolves through the import graph.
   ====================================================================== */
import './manifest.js';
import { initDom } from './ui/dom.js';
import { initList } from './ui/list.js';
import { initMenu } from './ui/menu.js';
import { initPanel, Panel } from './ui/panel.js';
import { Render } from './ui/renderer.js';
import { Report } from './services/report/index.js';
import { Interactions } from './app/interactions.js';
import { Controller } from './app/controller.js';
import { Settings } from './services/settings/index.js';
import { CONFIG } from './core/config.js';
import { Store } from './core/state.js';

initDom();
initList();
initMenu();
initPanel();

Panel.onToggle = Controller.togglePower;
Panel.onTool = Controller.toggleTool;
Panel.onBadgeControl = Controller.badgeControl;
Panel.onCopy = Report.copy;
Panel.onSweep = Controller.sweep;
Panel.onClear = Controller.clearPins;
Panel.onListOpen = (view) =>
  Panel.setList(Controller.rows(view), Controller.emptyFor(view));
Panel.onRowActivate = Controller.revealRow;
Panel.onRowRemove = Controller.removeRow;
Panel.onRowChange = Controller.changeRow;

// the page can remove a pinned element at any time; the list must not go on
// showing rows that no longer index into anything
Render.onPinsPruned = Controller.pinsPruned;

// before loadTools: a tool's options decide what its rules do, and arming
// one immediately schedules a render that asks
Settings.load();
Controller.refreshBadge();   // the 🏷 members show the values just loaded
Controller.loadTools();
Interactions.install(Controller);
/* THE SESSION SURVIVES THE REFRESH. Power is restored per origin, and the
   pins come back by selector — resolved against the page that exists NOW,
   with losses counted rather than hidden. Restored before the first paint,
   so a reload reads as a blink, not a reset. */
Controller.restorePins();
Controller.setPower(Store.get(`${CONFIG.POWER_KEY}:${location.origin}`) === '1');
