/* ======================================================================
  BOOT — the entry module: wire everything together and start

     Import order is not decorative. `./manifest.js` (generated by build.js)
     carries the side-effect registrations of every subject and tool, and it
     must run before initDom() builds the per-tool stylesheets. Everything
     else resolves through the import graph.
   ====================================================================== */
import './manifest.js';
import { initDom } from './ui/dom.js';
import { initList } from './ui/list.js';
import { initMenu } from './ui/menu.js';
import { initPanel, Panel } from './ui/panel.js';
import { Render } from './ui/renderer.js';
import { Report } from './services/report/index.js';
import { Interactions } from './app/interactions.js';
import { Bridge } from './app/bridge.js';
import { Updates } from './app/updates.js';
import { Controller } from './app/controller.js';
import { Settings } from './services/settings/index.js';
import { CONFIG } from './core/config.js';
import { Store } from './core/state.js';

initDom();
initList();
initMenu();
initPanel();

Panel.onToggle = Controller.togglePower;
Panel.onTool = Controller.toggleTool;
Panel.onBadgeControl = Controller.badgeControl;
Panel.onUpdateMenu = Updates.menu;
Panel.onCopy = Report.copy;
Panel.onSweep = Controller.sweep;
Panel.onClear = Controller.clearPins;
Panel.onListOpen = (view) =>
  Panel.setList(Controller.rows(view), Controller.emptyFor(view));
Panel.onRowActivate = Controller.revealRow;
Panel.onRowRemove = Controller.removeRow;
Panel.onRowChange = Controller.changeRow;
// the cockpit asks for a view's rows by name; the answer is the same pair
// the popover renders, so the two lists cannot diverge
Panel.onRowsFor = (view) => ({ rows: Controller.rows(view), empty: Controller.emptyFor(view) });

// the page can remove a pinned element at any time; the list must not go on
// showing rows that no longer index into anything
Render.onPinsPruned = Controller.pinsPruned;

/* The cockpit bridge listens to what the panel announces and replays it to
   the extension's side panel; commands come back on the callback slots wired
   above, so both faces are one code path. Wired BEFORE Settings.load and
   loadTools so its cache catches every setter call boot makes — a cockpit
   that connects later gets the truth replayed, not a blank bar. Under the
   userscript gate Bridge.init finds no chrome.runtime.onConnect and goes
   inert; onState stays cheap either way. */
Panel.onState = Bridge.state;
// a runtime's moments (a freeze landing) become cockpit timeline entries —
// same announce shape, and inert under the userscript gate like the rest
Controller.onToolEvent = Bridge.toolEvent;
Bridge.init();

// before loadTools: a tool's options decide what its rules do, and arming
// one immediately schedules a render that asks
Settings.load();
Controller.refreshBadge();   // the 🏷 members show the values just loaded
Controller.loadTools();
Interactions.install(Controller);
/* THE SESSION SURVIVES THE REFRESH. Power is restored per origin, and the
   pins come back by selector — resolved against the page that exists NOW,
   with losses counted rather than hidden. Restored before the first paint,
   so a reload reads as a blink, not a reset. */
Controller.restorePins();
Controller.setPower(Store.get(`${CONFIG.POWER_KEY}:${location.origin}`) === '1');
Updates.schedule();
